# Site settings
title: Bryne juletregard
email: juletrebryne@gmail.com
url: https://asmund1.github.io/bryne_juletregard/
description: "Plukk ut juletre på rot og hogge det sjøl eller velge blant våre utstilte ferdighogga juletre."
keywords: "juletre, sjølhogst, kranser, pyntegrønt"
skills:
meta_author:
christmas: true

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/bryne_juletregard"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Bryne juletregard
  location: Bryne juletregard
  social:
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/juletrebryne
  - title: instagram
    url: https://www.instagram.com/brynejuletregard


# Postal address (add as many lines as necessary)
address:
  - line: Brøytvegen 263, Bryne

# Credits content
credits:

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
